dist: xenial
os: linux
language: shell
stages:
  - name: "Test, Build and Deploy"
    if: branch =~ ^master$|^development$|^release
jobs:
  include:
    - stage: "Test, Build and Deploy"
      name: "Lint, Unit Test, Build and Deploy"
      language: node_js
      node_js: 12
      before_install: |-
        echo $TRAVIS_COMMIT
        echo $TRAVIS_TAG  
        echo $TRAVIS_BRANCH
        echo $TRAVIS_BUILD_NUMBER
        echo $TRAVIS_REPO_SLUG

      install: |-
        # install awscli v2 for ecr upload
        # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        # unzip /tmp/awscliv2.zip -d /tmp
        # sudo /tmp/aws/install

      before_script: |
        git config user.email "builds@travis-ci.com"
        git config user.name "Travis CI"
      script: |-
        # Start docker compose service
        docker-compose up -d
        # Run test
        yarn && yarn test
        # build the final image
        docker build -t travis-test-public:1.0.0 .
        docker tag travis-test-public:1.0.0 718530286671.dkr.ecr.us-east-2.amazonaws.com/travis-test-public:latest
      deploy:
        ## upload to ecr
        - provider: script
          script: >-
            AWS_REGISTRY_ID=718530286671
            AWS_REGION=us-east-2
            AWS_ACCESS_KEY_ID=AKIA2OS56CRH4SJYDR5U
            AWS_SECRET_ACCESS_KEY=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
            aws ecr get-login-password --region ${AWS_REGION}| docker login --username AWS --password-stdin
            ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
            && docker push 718530286671.dkr.ecr.us-east-2.amazonaws.com/travis-test-public:latest
            &&  aws ssm send-command
            --document-name "AWS-RunShellScript" 
            --targets '[{"Key":"InstanceIds","Values":["i-0b7c9597168140c61"]}]' 
            --parameters '{"commands":["sh /home/ec2-user/scripts/travis-test-public/restart.dev.sh"]}'
          cleanup: false
          on:
            all_branches: true
            condition: $REPO_SKIP_DEPLOY != "true"
